// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:1.9.0.77
//      SpecFlow Generator Version:1.9.0.0
//      Runtime Version:4.0.30319.34014
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace NSquared.MvcExtensions.Test
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "1.9.0.77")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [TechTalk.SpecRun.FeatureAttribute("使用ActionFilter提供測試資料", Description="為了方便在開發時期，可以在開發完成前先提供測試用的Api\n提供給前端開發人員 （F2E、App）\n透過Asp.Net Mvc Action Filter的方式，自" +
        "動讀取回傳對應的Json檔案並回傳", SourceFile="使用ActionFilter提供測試資料.feature", SourceLine=1)]
    public partial class 使用ActionFilter提供測試資料Feature
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "使用ActionFilter提供測試資料.feature"
#line hidden
        
        [TechTalk.SpecRun.FeatureInitialize()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("zh-TW"), "使用ActionFilter提供測試資料", "為了方便在開發時期，可以在開發完成前先提供測試用的Api\n提供給前端開發人員 （F2E、App）\n透過Asp.Net Mvc Action Filter的方式，自" +
                    "動讀取回傳對應的Json檔案並回傳", ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [TechTalk.SpecRun.FeatureCleanup()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        public virtual void TestInitialize()
        {
        }
        
        [TechTalk.SpecRun.ScenarioCleanup()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("HttpRequest包含Header，並且有測試資料，成功回傳測試資料", SourceLine=6)]
        public virtual void HttpRequest包含Header並且有測試資料成功回傳測試資料()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("HttpRequest包含Header，並且有測試資料，成功回傳測試資料", ((string[])(null)));
#line 7
this.ScenarioSetup(scenarioInfo);
#line 8
 testRunner.Given("HttpRequest的Header包含 \"NSquared-Request-Dummy\", 值為 \"True\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "假設");
#line 9
 testRunner.And("測試Json存在路徑 \"~/Dummy/Home/Dummy.json\"，內容為 \"{ \"id\" : 1 }\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "並且");
#line 10
 testRunner.When("執行Controller: \"Home\", Action: \"Dummy\" 時", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "當");
#line 11
 testRunner.Then("回傳內容為\"{ \"id\" : 1 }\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "那麼");
#line hidden
            this.ScenarioCleanup();
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("HttpRequest包含Header，但值為False，沒有覆寫回傳內容", SourceLine=12)]
        public virtual void HttpRequest包含Header但值為False沒有覆寫回傳內容()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("HttpRequest包含Header，但值為False，沒有覆寫回傳內容", ((string[])(null)));
#line 13
this.ScenarioSetup(scenarioInfo);
#line 14
 testRunner.Given("HttpRequest的Header包含 \"NSquared-Request-Dummy\", 值為 \"False\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "假設");
#line 15
 testRunner.And("測試Json存在路徑 \"~/Dummy/Home/Dummy.json\"，內容為 \"{ \"id\" : 1 }\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "並且");
#line 16
 testRunner.When("執行Controller: \"Home\", Action: \"Dummy\" 時", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "當");
#line 17
 testRunner.Then("沒有回傳內容", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "那麼");
#line hidden
            this.ScenarioCleanup();
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("HttpRequest沒有包含Header，沒有覆寫回傳內容", SourceLine=18)]
        public virtual void HttpRequest沒有包含Header沒有覆寫回傳內容()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("HttpRequest沒有包含Header，沒有覆寫回傳內容", ((string[])(null)));
#line 19
this.ScenarioSetup(scenarioInfo);
#line 20
 testRunner.Given("測試Json存在路徑 \"~/Dummy/Home/Dummy.json\"，內容為 \"{ \"id\" : 1 }\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "假設");
#line 21
 testRunner.When("執行Controller: \"Home\", Action: \"Dummy\" 時", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "當");
#line 22
 testRunner.Then("沒有回傳內容", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "那麼");
#line hidden
            this.ScenarioCleanup();
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("HttpRequest包含Header，預設路徑沒有資料，收到錯誤訊息", SourceLine=23)]
        public virtual void HttpRequest包含Header預設路徑沒有資料收到錯誤訊息()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("HttpRequest包含Header，預設路徑沒有資料，收到錯誤訊息", ((string[])(null)));
#line 24
this.ScenarioSetup(scenarioInfo);
#line 25
 testRunner.Given("HttpRequest的Header包含 \"NSquared-Request-Dummy\", 值為 \"True\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "假設");
#line 26
 testRunner.And("沒有測試用的Json", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "並且");
#line 27
 testRunner.When("執行Controller: \"Home\", Action: \"Dummy\" 時", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "當");
#line 28
 testRunner.Then("拋出錯誤訊息", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "那麼");
#line hidden
            this.ScenarioCleanup();
        }
        
        [TechTalk.SpecRun.TestRunCleanup()]
        public virtual void TestRunCleanup()
        {
TechTalk.SpecFlow.TestRunnerManager.GetTestRunner().OnTestRunEnd();
        }
    }
}
#pragma warning restore
#endregion
